version: '3'

services:
  app:
    container_name: FastAPI
    build: .
    volumes:
      - ./src:/app
    ports:
      - "8080:8080"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: irroba
      MONGO_INITDB_ROOT_PASSWORD: irr157ba
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: irroba
      ME_CONFIG_MONGODB_ADMINPASSWORD: irr157ba
      ME_CONFIG_MONGODB_URL: mongodb://irroba:irr157ba@mongo:27017/